### PR TITLE
Adding the http method as a parameter to the execeute call

### PR DESCRIPTION
**Pull request by aritrod**
@pbathia @renujhamtani please review and merge !

### CODE REVIEW

**Comment by pbathia** [comment]
@ardasgup have you tried any 'post' method just for testing? As if the method is post, we will need data field also,until this it wont be generic. Also we should consider this method for replacing executeUdsAjaxCallWithData.

**Comment by aritrod** [comment]
@pbathia i intentionally kept the executeUdsAjaxCallWithData method which would handle the POST calls, all POST calls should have some data. We could work out some way of addressing even that under data: but for now i think we should be good with just that.

**Comment by pbathia** [comment]
@ardasgup i think I have not got what extra will get achieved with this then?

**Comment by aritrod** [comment]
@pbathia we cannot make a DELETE call without the above change.

**Comment by pbathia** [comment]
@ardasgup  ok.

**Pull request merged**
