### PR TITLE
Private and Public comments API

### PR DESCRIPTION
**Pull request by renujhamtani**
@sshumake @pbathia Please review. This is dependent on public and private comments. I am not sure why this commit of merging had unnecessary files.

### CODE REVIEW

**Comment by pbathia** [comment]
Renu, this is because while merging permissions of the files got changed. You can easily revert the permission using chmod command.

**Comment by pbathia** [comment]
Code looks good.

**Comment by renujhamtani** [comment]
@pbathia I have reverted the permissions thing...please check

**Comment by pbathia** [comment]
We can merge now.

**Pull request merged**
