### PR TITLE
PCM-3090: Added user-role update API

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur Please review.

https://projects.engineering.redhat.com/browse/PCM-3090

Adding the user-role update API mentioned in https://projects.engineering.redhat.com/browse/UNIFIED-1321.

### CODE REVIEW

**Comment by jtrantin** [comment]
Just realized I will need some more changes, don't review and merge, I will update this PR..

**Comment by renujhamtani** [comment]
@jtrantin take the latest and update the version too. I just merged long pending one of Vikas. Will publish it now.

**Comment by jtrantin** [comment]
@vrathee @gandhikeyur Updated the PR, please review!

**Comment by vrathee** [comment]
Reviewed.. Looks Good..

**Comment by gandhikeyur** [comment]
Reviewed

**Pull request merged**
