### PR TITLE
PCM-287: Moving to a webpack based build

### PR DESCRIPTION
**Pull request by engineersamuel**
https://projects.engineering.redhat.com/browse/PCM-2872

Moving udsjs to webpack build.  The benefits are:
- Modular build system, so we can import individual functions instead of requiring the entire udsjs.  This isn't such an issue since udsjs is small, but having a modular build is always a good thing. 
- One of the largest benefit is these changes pave the way to begin eliminating the necessity of binding libraries to global vars (Uri, uds, ect..)  Then we can start really modularizing ascension with imports into individual files.
- ES6 all the things!

### CODE REVIEW

**Comment by engineersamuel** [comment]
@gandhikeyur @vrathee @jtrantin please review.

We'll need to push this to npm as well.  It can be pushed to bower as well, it should just work like it did before with no changes required, I haven't tested the publishing though.   I'm not sure who would push to npm, I'm assuming @vrathee or @renujhamtani

**Comment by engineersamuel** [comment]
Another note here.  When published, I have an npm script called 'prepublish'  this should be called automatically by npm publish to generate dist/uds.js and dist/uds.min.js.  See https://docs.npmjs.com/misc/scripts, you shouldn't need to run it, just npm publish (but again I haven't tested this).  This let's us keep the dist/\* out of git.

**Comment by jtrantin** [comment]
1) I don't think we can keep dist/\* out of git AND still push to bower. AFAIK bower takes the artifacts from the GIT repository (under a certain tag), and therefore the repository should contain the built distribution. That is if we decide not to drop bower.

2) Do we really want to modularize up to the method-level? It seems kinda strange to be honest, as e.g. you would be generally injecting lot of methods anyway. To me it would make more sense to divide udsjs into more objects that would encapsulate related calls. E.g. an object for User/roles related calls; object for Case related calls; Reviews related calls;... Ideas?

**Comment by engineersamuel** [comment]
For 1) it's been a while since I used bower though I had hoped it was intelligent enough to whitelist the package.main field which is `"main": "dist/uds.js"` and blacklist all of the paths/files in the package.ignore.  This may not be the case, but have we tried it to see?

For 2) this is really just standard ES6 stuff: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export  Exporting named functions let's you import each one individually in whatever parent file you are in.  You may ask why this matters.  For a library this small it has a minimal impact on size, but it is nice for the modularity and the potentially chunking we can do.

There were three options I could have used to rewrite uds.js, 1) An exported ES6 class, 2) An exported uds = {} object and 3) The way I did it with individually exported named functions.  The problem with 2) is that we would have to rewrite the upstream as exporting an object like this puts it in the 'default' namespace.  This works fine with other ES6 things using import but not require or just putting the file in an index.html, hence I chose the individually exported functions which are backwards compatible.  

Have you looked at the babel generated code?  Build it and check it out, it is very reasonable and gives us npm + bower + global, and it looks very similar to before.  The exported functions translate fine in the transpiled code.

**Comment by jtrantin** [comment]
ad 1) The thing is we need to have dist/uds.js in git in order to work. I am not very sure of how bower works, but I would say it doesn't check package.json, since it has its own bower.json file. Anyways the problem is not that other files are included, the issue is we need to include dist/uds.js in the git repo.

ad 2) OK, it just seemed strange at first, but as long as it provides advantages (which it does, backwards compatibility is great!) then I am OK with it. I am still more used to importing (larger) objects, rather than methods.

**Comment by engineersamuel** [comment]
I think I have a good solution for 1) then.  We can keep dist/uds.js in git, but exclude dist/uds.min.js.  That way the git commits won't look terrible, and we can still publish the minified code through npm.  We will probably ultimately phase out bower from the front end so having the minified in bower isn't a problem.

We still don't have to import individual methods.  Even with the new build you can `const uds = require('uds')` and it just works.  The biggest benefit is now we can import individual methods into individual controllers and services so then the webpack build can be made much more intelligent in the future.

**Comment by vrathee** [comment]
Looks Good! Reviewed!

**Comment by gandhikeyur** [comment]
Reviewed..
Will merge and publish a new tag.

**Pull request merged**
