### PR TITLE
PCM-3196: Adding bugzilla and bugzilla comment apis

### PR DESCRIPTION
**Pull request by engineersamuel**
https://projects.engineering.redhat.com/browse/PCM-3196

Adding in the api for bugzillas and bugzilla comments in preparation for chatter.

### CODE REVIEW

**Comment by engineersamuel** [comment]
@jtrantin @gandhikeyur @vrathee Please review.

**Comment by jtrantin** [comment]
Looks good. Reviewed.

**Comment by renujhamtani** [comment]
Looks good!

**Comment by renujhamtani** [comment]
@engineersamuel  Change the version in package.json and bower.json and then merge it,release it and publish it. I guess you have the rights to npm publish? If not, @jtrantin has it and he can even give the rights. I am OOO tomorrow (pune public holiday).

**Comment by engineersamuel** [comment]
@renujhamtani done, I don't have the publishing info, will sync up with @jtrantin or @vrathee

**Pull request merged**
